const products = [
  {
    id: 1,
    image: "/images/notebooks.jpg",
    name: "Notebooks",
    price: 5,
    description: "Fancy notebooks with colorful covers, 80 pages.",
  },
  {
    id: 2,
    image: "/images/calculator.jpg",
    name: "Calculator",
    price: 3,
    description: "Durable calculator for basic and scientific calculations.",
  },
  {
    id: 3,
    image: "/images/pencils.jpg",
    name: "Pencils",
    price: 4,
    description: "Pack of 10 high-quality HB pencils.",
  },
  {
    id: 4,
    image: "/images/erasers.jpg",
    name: "Erasers",
    price: 2,
    description: "Soft erasers that remove pencil marks cleanly.",
  },
  {
    id: 5,
    image: "/images/pens.jpg",
    name: "Pens",
    price: 6,
    description: "Set of 5 smooth-flow ink pens in various colors.",
  },
  {
    id: 6,
    image: "/images/highlighters.jpg",
    name: "Highlighters",
    price: 7,
    description: "Bright fluorescent highlighters in a pack of 6.",
  },
  {
    id: 7,
    image: "/images/gluesticks.jpg",
    name: "Glue Sticks",
    price: 3,
    description: "Non-toxic glue sticks for arts and crafts.",
  },
  {
    id: 8,
    image: "/images/ruler.jpg",
    name: "Ruler",
    price: 2,
    description: "Shatterproof ruler with clear markings.",
  },
  {
    id: 9,
    image: "/images/stapler.jpg",
    name: "Stapler",
    price: 8,
    description: "Compact stapler with a box of 200 staples included.",
  },
  {
    id: 10,
    image: "/images/markers.jpg",
    name: "Markers",
    price: 10,
    description: "Set of 7 colorful, washable markers.",
  },
  {
    id: 11,
    image: "/images/indexcards.jpg",
    name: "Index Cards",
    price: 4,
    description: "Pack of ruled index cards for study notes.",
  },
  {
    id: 12,
    image: "/images/backpack.jpg",
    name: "Backpack",
    price: 25,
    description: "Durable school backpack with multiple compartments.",
  },
  {
    id: 13,
    image: "/images/geometryset.jpg",
    name: "Geometry Set",
    price: 8,
    description: "Complete geometry set with compass, protractor, and ruler.",
  },
  {
    id: 14,
    image: "/images/scissors.jpg",
    name: "Scissors",
    price: 3,
    description: "Safety scissors with comfortable grip handles.",
  },
];

export default products;
